// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.queryBetweenBrokenStmt, err = db.PrepareContext(ctx, queryBetweenBroken); err != nil {
		return nil, fmt.Errorf("error preparing query QueryBetweenBroken: %w", err)
	}
	if q.queryBetweenNamedBrokenStmt, err = db.PrepareContext(ctx, queryBetweenNamedBroken); err != nil {
		return nil, fmt.Errorf("error preparing query QueryBetweenNamedBroken: %w", err)
	}
	if q.queryBetweenNamedWorkingStmt, err = db.PrepareContext(ctx, queryBetweenNamedWorking); err != nil {
		return nil, fmt.Errorf("error preparing query QueryBetweenNamedWorking: %w", err)
	}
	if q.queryBetweenWorkingStmt, err = db.PrepareContext(ctx, queryBetweenWorking); err != nil {
		return nil, fmt.Errorf("error preparing query QueryBetweenWorking: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.queryBetweenBrokenStmt != nil {
		if cerr := q.queryBetweenBrokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryBetweenBrokenStmt: %w", cerr)
		}
	}
	if q.queryBetweenNamedBrokenStmt != nil {
		if cerr := q.queryBetweenNamedBrokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryBetweenNamedBrokenStmt: %w", cerr)
		}
	}
	if q.queryBetweenNamedWorkingStmt != nil {
		if cerr := q.queryBetweenNamedWorkingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryBetweenNamedWorkingStmt: %w", cerr)
		}
	}
	if q.queryBetweenWorkingStmt != nil {
		if cerr := q.queryBetweenWorkingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queryBetweenWorkingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	queryBetweenBrokenStmt       *sql.Stmt
	queryBetweenNamedBrokenStmt  *sql.Stmt
	queryBetweenNamedWorkingStmt *sql.Stmt
	queryBetweenWorkingStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		queryBetweenBrokenStmt:       q.queryBetweenBrokenStmt,
		queryBetweenNamedBrokenStmt:  q.queryBetweenNamedBrokenStmt,
		queryBetweenNamedWorkingStmt: q.queryBetweenNamedWorkingStmt,
		queryBetweenWorkingStmt:      q.queryBetweenWorkingStmt,
	}
}
