// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package sqlc

import (
	"context"
)

const queryBetween = `-- name: QueryBetween :many
SELECT id FROM test
WHERE name = ?
AND id BETWEEN ? AND ?
`

func (q *Queries) QueryBetween(ctx context.Context, name string) ([]int64, error) {
	rows, err := q.query(ctx, q.queryBetweenStmt, queryBetween, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
